### PR TITLE
Algo v0.1

### PR DESCRIPTION
**Pull request by JZhang0**
I've implemented a prototype version of the algorithm, it works fairly well on the "Volcanic Rocks" samples but not ideal for the "Impact Rocks".

Some of the new functions added:
1. Background removal.
2. Auto contrast adjustment.
3. Auto despeckle based on input image's size.
4. Morphology operations(erosion, dilasion, opening, closing).
5. Auto thresholding.

Also I've added a test.java file which is the prototype of the algorithm, change the name of the input file to test on different files.

Some of the sample outputs in comparision with manual result:
<p align="center">
  airfall1
&nbsp; &nbsp; &nbsp; &nbsp;
  airfall0
</p>

<p align="center">
  middle1
&nbsp; &nbsp; &nbsp; &nbsp;
  middle0
</p>

<p align="center">
  upper1
&nbsp; &nbsp; &nbsp; &nbsp;
  upper0
</p>

<p align="center">
  MI_CC_06_0
&nbsp; &nbsp; &nbsp; &nbsp;
  MI_CC_06_1
</p>

<p align="center">
  MI_CC_04_0
&nbsp; &nbsp; &nbsp; &nbsp;
  MI_CC_04_1
</p>

Todo: 

1. Currently the algorithm does not work well with rocks with colored melt(i.e. not black), I think this could be improved by splitting the image channels and pick one where the contrast between melt and ground mass is high.
2. Need to fill the holes in some cases and create a binary image where the melt is black for data processing purpose.

### CODE REVIEW

**Review by yzha3296 — COMMENTED** [review]
good

**Review by yzha3296 — COMMENTED** [review]
good

**Review by njacobs6 — APPROVED** [review]

**Comment by yzha3296** [comment]
approved

**Review by yzha3296 — APPROVED** [review]
approve

**Pull request merged**
